x=float(input('Please enter number to take square root of: '))
guess=1
guess=.5*(guess+x/guess)
guess=.5*(guess+x/guess)
guess=.5*(guess+x/guess)
guess=.5*(guess+x/guess)
guess=.5*(guess+x/guess)
guess=.5*(guess+x/guess)
guess=.5*(guess+x/guess)
guess=.5*(guess+x/guess)
guess=.5*(guess+x/guess)
guess=.5*(guess+x/guess)
guess=.5*(guess+x/guess)
guess=.5*(guess+x/guess)
guess=.5*(guess+x/guess)
guess=.5*(guess+x/guess)
guess=.5*(guess+x/guess)
print(guess)
print('compare with the actual square root:',x**.5)
